### ISSUE TITLE
deprecated methods symfony 3.*

### ISSUE THREAD

**Issue by yanict** [genemu/GenemuFormBundle#426] opened 2016-05-23 11:35 UTC
could the bundle be updated to be compatible with symfony 3.* ?
there is a lot of deprecated methods and symfony will already release 3.2 in a few months.
otherwise most of users will have to find an alternative option and this nice bundle will be forsaken.

thanks a lot

**Comment by bamarni** [comment] 2016-05-23 13:04
> otherwise most of users will have to find an alternative option and this nice bundle will be forsaken

I wouldn't be that pessimistic, some others might just send PRs :-)

(Closing as duplicate of #425)

**Closed by bamarni** 2016-05-23 13:04 UTC
